<div id="main_menu_lspacer_sub"></div>
          <div id="main_menu_buy_tickets"><a href="http://www.ticketmaster.com/event/0C004182E3DEDCF6?artistid=753775&amp;majorcatid=10001&amp;minorcatid=50" target="_blank"><img src="images/main_menu_buy_tickets.png" alt="Buy Tickets" name="Image1" width="89" height="30" border="0" id="Image1" onmouseover="MM_swapImage('Image1','','images/main_menu_buy_ticketsB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
<div id="main_menu_invite"><a href="invite.php"><img src="images/main_menu_invite.png" alt="Invite a Friend" name="Image2" width="110" height="30" border="0" id="Image2" onmouseover="MM_swapImage('Image2','','images/main_menu_inviteB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
<div id="main_menu_FAQ"><a href="http://www.mormontabernaclechoir.org/faq" target="_blank"><img src="images/main_menu_FAQ.png" alt="FAQ" name="Image3" width="49" height="30" border="0" id="Image3" onmouseover="MM_swapImage('Image3','','images/main_menu_FAQB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
<div id="main_menu_choir_facts"><a href="http://www.mormontabernaclechoir.org/info/" target="_blank"><img src="images/main_menu_choir_facts.png" alt="Choir History" name="Image4" width="92" height="30" border="0" id="Image4" onmouseover="MM_swapImage('Image4','','images/main_menu_choir_factsB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
      
<div id="main_menu_videos"><a href="http://newsroom.lds.org/ldsnewsroom/eng/background-information/mormon-tabernac
le-choir#current" target="_blank"><img src="images/main_menu_videos.png" alt="Videos" name="Image25" width="63" height="30" border="0" id="Image25" onmouseover="MM_swapImage('Image25','','images/main_menu_videosB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
      
          <div id="main_menu_2009_tour"><a href="http://www.mormontabernaclechoir.org/events/" target="_blank"><img src="images/main_menu_2009_tour.png" alt="2009 Tour" name="Image5" width="83" height="30" border="0" id="Image5" onmouseover="MM_swapImage('Image5','','images/main_menu_2009_tourB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
<div id="main_menu_venue"><a href="venue.php"><img src="images/main_menu_venue.png" alt="Venue" name="Image6" width="61" height="30" border="0" id="Image6" onmouseover="MM_swapImage('Image6','','images/main_menu_venueB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
<div id="main_menu_sponsorship"><a href="sponsorship.php"><img src="images/main_menu_sponsorship.png" alt="Sponsorship" name="Image7" width="94" height="30" border="0" id="Image7" onmouseover="MM_swapImage('Image7','','images/main_menu_sponsorshipB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
<div id="main_menu_contact"><a href="contact.php"><img src="images/main_menu_contact.png" alt="Contact" name="Image8" width="69" height="30" border="0" id="Image8" onmouseover="MM_swapImage('Image8','','images/main_menu_contactB.png',1)" onmouseout="MM_swapImgRestore()" /></a></div>
<div id="main_menu_rspacer_sub"></div>